name: Wild
author: BlazeTheDev
version: 1.0.0
description: A wild teleporting plugin for PocketMine
main: iiFlamiinBlaze\Wild\Wild
api: 3.0.0-ALPHA12
commands:
 wild:
  description: Teleports you to a random location
  permission: wild.command
permissions:
 wild.command:
  default: true