name: Feed-Heal
version: 1.0.0
api: [3.0.0-ALPHA9, 2.1.0, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12]
author: georgianYT
main: Feed\Heal\FHMain
commands:
  heal:
    description: "To heal players"
    aliases: [Heal]
  feed:
    description: "To feed players"
    aliases: [Feed]
permissions:
  server.heal:
    description: "Heal perm"
    default: false
  server.feed:
    description: "Feed perm"
    default: false